#  charts/common/templates/secret.yaml
# ==========================================


apiVersion: v1
kind: Secret
metadata:
  name: {{ include "banking.fullname" . }}-secret
type: Opaque
data:
  DB_USERNAME: {{ .Values.db.username | b64enc }}
  DB_PASSWORD: {{ .Values.db.password | b64enc }}