#Secret.yaml
#===============

apiVersion: v1
kind: Secret
metadata:
  name: customer-care-secret
type: Opaque
stringData:
  DB_USERNAME: "user"
  DB_PASSWORD: "password"
  
  
  =========== if you have user and password in a file ======================
all_users.json
------------------
  
  {
  "users": [
    {"username": "cm_db_user", "password": "password1"},
    {"username": "dm_db_user", "password": "password2"},
    {"username": "mx3user", "password": "password3"}
  ]
}

cat all_users.json | base64  -----------> the output will be  <base64-encoded-content>

you can create secret as below

apiVersion: v1
kind: Secret
metadata:
  name: db-users-secret
type: Opaque
data:
  all_users.json: <base64-encoded-content>
  
				or
				
kubectl create secret generic db-users-secret --from-file=all_users.json   ( recomended )

to use this secret db-users-secret mount it in the volume



  
  
 